spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/back_to_you
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

server.port=8081